const WALLET = {
    WALLET_CREDIT: "WALLET_CREDIT",
    WALLET_CREDIT_SUCCESS: "WALLET_CREDIT_SUCCESS",
    WALLET_CREDIT_FAILED: "WALLET_CREDIT_FAILED",
    WALLET_DEBIT: "WALLET_DEBIT",
    WALLET_DEBIT_SUCCESS: "WALLET_DEBIT_SUCCESS",
    WALLET_DEBIT_FAILED: "WALLET_DEBIT_FAILED",
};

export default WALLET;
