const WORDPRESS = {
    WP_LOGS: "WP_LOGS",
    WP_LOGS_SUCCESS: "WP_LOGS_SUCCESS",
    WP_LOGS_FAILED: "WP_LOGS_FAILED",
    WP_LOGS_APPROVE: "WP_LOGS_APPROVE",
    WP_LOGS_APPROVE_SUCCESS: "WP_LOGS_APPROVE_SUCCESS",
    WP_LOGS_APPROVE_FAILED: "WP_LOGS_APPROVE_FAILED",
};
export default WORDPRESS;
