const OPERATION = {
    CACHE_PUT: "CACHE_PUT",
    CACHE_PUT_SUCCESS: "CACHE__PUTSUCCESS",
    CACHE_PUT_FAILED: "CACHE_PUT_FAILED",
    PERMISSIONS_GET: "PERMISSIONS_GET",
    PERMISSIONS_GET_SUCCESS: "PERMISSIONS_GET_SUCCESS",
    PERMISSIONS_GET_FAILED: "PERMISSIONS_GET_FAILED",
    BOT_PUT: "BOT_PUT",
    BOT_PUT_SUCCESS: "BOT_PUT_SUCCESS",
    BOT_PUT_FAILED: "BOT_PUT_FAILED",
};
export default OPERATION;
