const OPERATION = {
    CACHE_PUT: "CACHE_PUT",
    CACHE_PUT_SUCCESS: "CACHE__PUTSUCCESS",
    CACHE_PUT_FAILED: "CACHE_PUT_FAILED",
    PERMISSIONS_RESET: "PERMISSIONS_RESET",
    PERMISSIONS_RESET_SUCCESS: "PERMISSIONS_RESET_SUCCESS",
    PERMISSIONS_RESET_FAILED: "PERMISSIONS_RESET_FAILED",
};

export default OPERATION;
