const MIGRATION = {
	MIGRATIONS_FILTER: "MIGRATIONS_FILTER",
	MIGRATIONS_FILTER_SUCCESS: "MIGRATIONS_FILTER_SUCCESS",
	MIGRATIONS_FILTER_FAILED: "MIGRATIONS_FILTER_FAILED",
};

export default MIGRATION;
