const UPDATEALL = {
	UPDATEALL_GET: "UPDATEALL_GET",
	UPDATEALL_GET_SUCCESS: "UPDATEALL_GET_SUCCESS",
	UPDATEALL_GET_FAILED: "UPDATEALL_GET_FAILED",
	UPDATEALL_PUT: "UPDATEALL_PUT",
	UPDATEALL_PUT_SUCCESS: "UPDATEALL_PUT_SUCCESS",
	UPDATEALL_PUT_FAILED: "UPDATEALL_PUT_FAILED",
};

export default UPDATEALL;
