const ONECLICKLOGIN = {
	ONECLICKLOGIN_GET: "ONECLICKLOGIN_GET",
	ONECLICKLOGIN_GET_SUCCESS: "ONECLICKLOGIN_GET_SUCCESS",
	ONECLICKLOGIN_GET_FAILED: "ONECLICKLOGIN_GET_FAILED",
};

export default ONECLICKLOGIN;
