const WORDPRESS = {
	WORDPRESS_UPDATE_PUT: "WORDPRESS_UPDATE_PUT",
	WORDPRESS_UPDATE_PUT_SUCCESS: "WORDPRESS_UPDATE_PUT_SUCCESS",
	WORDPRESS_UPDATE_PUT_FAILED: "WORDPRESS_UPDATE_PUT_FAILED",
};

export default WORDPRESS;
