const USER_DETAILS = {
	USER_DETAILS_GET: "USER_DETAILS_GET",
	USER_DETAILS_GET_SUCCESS: "USER_DETAILS_GET_SUCCESS",
	USER_DETAILS_GET_FAILED: "USER_DETAILS_GET_FAILED",
};

export default USER_DETAILS;
