const SITE_DETAILS = {
	SITE_DETAILS_GET: "SITE_DETAILS_GET",
	SITE_DETAILS_GET_SUCCESS: "SITE_DETAILS_GET_SUCCESS",
	SITE_DETAILS_GET_FAILED: "SITE_DETAILS_GET_FAILED",
};

export default SITE_DETAILS;
