const VOUCHER = {
    VOUCHER_GET: "VOUCHER_GET",
    VOUCHER_GET_SUCCESS: "VOUCHER_GET_SUCCESS",
    VOUCHER_GET_FAILED: "VOUCHER_GET_FAILED",
    VOUCHER_FIRST: "VOUCHER_FIRST",
    VOUCHER_FIRST_SUCCESS: "VOUCHER_FIRST_SUCCESS",
    VOUCHER_FIRST_FAILED: "VOUCHER_FIRST_FAILED",
    VOUCHER_DELETE: "VOUCHER_DELETE",
    VOUCHER_DELETE_SUCCESS: "VOUCHER_DELETE_SUCCESS",
    VOUCHER_DELETE_FAILED: "VOUCHER_DELETE_FAILED",
    VOUCHER_POST: "VOUCHER_POST",
    VOUCHER_POST_SUCCESS: "VOUCHER_POST_SUCCESS",
    VOUCHER_POST_FAILED: "VOUCHER_POST_FAILED",
    VOUCHER_PUT: "VOUCHER_PUT",
    VOUCHER_PUT_SUCCESS: "VOUCHER_PUT_SUCCESS",
    VOUCHER_PUT_FAILED: "VOUCHER_PUT_FAILED",
};
export default VOUCHER;
