const WORDPRESS = {
	WORDPRESS_REFRESH: "WORDPRESS_REFRESH",
	WORDPRESS_REFRESH_SUCCESS: "WORDPRESS_REFRESH_SUCCESS",
	WORDPRESS_REFRESH_FAILED: "WORDPRESS_REFRESH_FAILED",
};

export default WORDPRESS;
