const DATACENTER = {
	DATACENTER_DELETE: "DATACENTER_DELETE",
	DATACENTER_DELETE_SUCCESS: "DATACENTER_DELETE_SUCCESS",
	DATACENTER_DELETE_FAILED: "DATACENTER_DELETE_FAILED",
};

export default DATACENTER;
