const MIGRATION = {
    MIGRATION_TRASH: "MIGRATION_TRASH",
    MIGRATION_TRASH_SUCCESS: "MIGRATION_TRASH_SUCCESS",
    MIGRATION_TRASH_FAILED: "MIGRATION_TRASH_FAILED",
};

export default MIGRATION;
