const CUSTOMER_DETAILS = {
	CUSTOMER_DETAILS_GET: "CUSTOMER_DETAILS_GET",
	CUSTOMER_DETAILS_GET_SUCCESS: "CUSTOMER_DETAILS_GET_SUCCESS",
	CUSTOMER_DETAILS_GET_FAILED: "CUSTOMER_DETAILS_GET_FAILED",
};

export default CUSTOMER_DETAILS;
