const ROLE_DETAILS = {
	ROLE_DETAILS_GET: "ROLE_DETAILS_GET",
	ROLE_DETAILS_GET_SUCCESS: "ROLE_DETAILS_GET_SUCCESS",
	ROLE_DETAILS_GET_FAILED: "ROLE_DETAILS_GET_FAILED",
};

export default ROLE_DETAILS;
