const INVOICE_DETAILS = {
	INVOICE_DETAILS_GET: "INVOICE_DETAILS_GET",
	INVOICE_DETAILS_GET_SUCCESS: "INVOICE_DETAILS_GET_SUCCESS",
	INVOICE_DETAILS_GET_FAILED: "INVOICE_DETAILS_GET_FAILED",
};

export default INVOICE_DETAILS;
