const CUSTOMER = {
    CUSTOMER_FIRST_V3: "CUSTOMER_FIRST_V3",
    CUSTOMER_FIRST_SUCCESS_V3: "CUSTOMER_FIRST_SUCCESS_V3",
    CUSTOMER_FIRST_FAILED_V3: "CUSTOMER_FIRST_FAILED_V3",
};
export default CUSTOMER;
