const CUSTOMER = {
    CUSTOMER_INVOICE: "CUSTOMER_INVOICE",
    CUSTOMER_INVOICE_SUCCESS: "CUSTOMER_INVOICE_SUCCESS",
    CUSTOMER_INVOICE_FAILED: "CUSTOMER_INVOICE_FAILED",
};

export default CUSTOMER;
