const OPERATION = {
    REDIS_FIRST: "REDIS_FIRST",
    REDIS_FIRST_SUCCESS: "REDIS_FIRST_SUCCESS",
    REDIS_FIRST_FAILED: "REDIS_FIRST_FAILED",
    REDIS_TOGGLE: "REDIS_TOGGLE",
    REDIS_TOGGLE_SUCCESS: "REDIS_TOGGLE_SUCCESS",
    REDIS_TOGGLE_FAILED: "REDIS_TOGGLE_FAILED",
    REDIS_DELETE: "REDIS_DELETE",
    REDIS_DELETE_SUCCESS: "REDIS_DELETE_SUCCESS",
    REDIS_DELETE_FAILED: "REDIS_DELETE_FAILED",
};

export default OPERATION;
