const PREMIUM = {
    PREMIUM_GET: "PREMIUM_GET",
    PREMIUM_GET_SUCCESS: "PREMIUM_GET_SUCCESS",
    PREMIUM_GET_FAILED: "PREMIUM_GET_FAILED",
    PREMIUM_FIRST: "PREMIUM_FIRST",
    PREMIUM_FIRST_SUCCESS: "PREMIUM_FIRST_SUCCESS",
    PREMIUM_FIRST_FAILED: "PREMIUM_FIRST_FAILED",
    PREMIUM_DELETE: "PREMIUM_DELETE",
    PREMIUM_DELETE_SUCCESS: "PREMIUM_DELETE_SUCCESS",
    PREMIUM_DELETE_FAILED: "PREMIUM_DELETE_FAILED",
    PREMIUM_POST: "PREMIUM_POST",
    PREMIUM_POST_SUCCESS: "PREMIUM_POST_SUCCESS",
    PREMIUM_POST_FAILED: "PREMIUM_POST_FAILED",
    PREMIUM_PUT: "PREMIUM_PUT",
    PREMIUM_PUT_SUCCESS: "PREMIUM_PUT_SUCCESS",
    PREMIUM_PUT_FAILED: "PREMIUM_PUT_FAILED",
};
export default PREMIUM;
